
#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_LDM.EDM_LDM"

# SDE hyperparameters
type: "ve_karras"

AE_type: "Music2Latent4" 

cfg_dropout_prob: 0.5

sde_hp:
  sigma_data: 0.5 #default for maestro
  sigma_min: 1e-2
  sigma_max: 100
  rho: 10
  max_sigma: 100

default_shape: [1, 64, 128]

context_preproc: 
  to_mono: True
  add_noise: True
  noise_type: "pink"
  SNR_mean: 0.0
  SNR_std: 2.0


effect_randomizer:
    _target_: utils.fx_randomization.randomizers.ReverbRandomizer
    range_coloration: 2
    min_T60: 0.2
    max_T60: 1.5
    sample_rate: ${exp.sample_rate}
    ir_len: ${exp.sample_rate}
    batch_size: ${exp.batch_size}
    drywet_ratio_min: 0.0
    drywet_ratio_max: 1.0
  
effect_randomizer_test:
    _target_: utils.fx_randomization.randomizers.ReverbRandomizer
    range_coloration: 0
    min_T60: 0.3
    max_T60: 0.3
    sample_rate: ${exp.sample_rate}
    ir_len: ${exp.sample_rate}
    batch_size: ${exp.batch_size}
    drywet_ratio_min: 0.9
    drywet_ratio_max: 0.9