#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_style.EDM_Style"

# SDE hyperparameters
type: "ve_karras"

AE_type: "Music2Latent4" #used for encoding the context

FXenc_args:
  type: "AFxRep"
  ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/tmp/afx-rep.ckpt"

sample_rate: 44100

cfg_dropout_prob: 0.2

sde_hp:
  sigma_data: 0.044 #default for maestro
  sigma_min: 1e-4
  sigma_max: 10
  max_sigma: 10
  rho: 10

default_shape: [1, 1024, 1] 