#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_style.EDM_Style"

# SDE hyperparameters
type: "ve_karras"

AE_type: "oracle" #used for encoding the context

FXenc_args:
  type: "AFxRep"
  ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/tmp/afx-rep.ckpt"

sample_rate: 44100

cfg_dropout_prob: 0.2

sde_hp:
  sigma_data: 0.044 #default for maestro
  sigma_min: 1e-5
  sigma_max: 10
  max_sigma: 10
  rho: 10

MERT_args:
  layer: 8 #use the last layer of the MERT model
  average: True #if True, the features will be averaged over time
  normalize: True

oracle_args:
  size: 64 #size of the oracle features

apply_fxnormaug: False
fxnormaug_train:
  _target_: fx_model.fxnormaug_v0.FxNormAug
  sample_rate: 44100
  mode: "train"
  device: "cuda"

fxnormaug_inference:
  _target_: fx_model.fxnormaug_v0.FxNormAug
  sample_rate: 44100
  mode: "inference"
  device: "cuda"

default_shape: [1, 64, 16] 

