#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_LDM.EDM_LDM"

# SDE hyperparameters
type: "ve_karras"

AE_type: "Music2Latent" 

sde_hp:
  sigma_data: 1 #default for maestro
  sigma_min: 1e-4
  sigma_max: 400
  rho: 10
  max_sigma: 10
