#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_LDM.EDM_LDM"

# SDE hyperparameters
type: "ve_karras"

AE_type: "SAO_VAE" 

cfg_dropout_prob: 0.5

sde_hp:
  sigma_data: 1 #default for maestro
  sigma_min: 1e-4
  sigma_max: 400
  max_sigma: 400
  rho: 10


default_shape: [1, 64, 256]