#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_LDM.EDM_LDM"

# SDE hyperparameters
type: "ve_karras"

AE_type: "Music2Latent4" 

cfg_dropout_prob: 0.5

sde_hp:
  sigma_data: 0.5 #default for maestro
  sigma_min: 1e-4
  sigma_max: 100
  max_sigma: 100
  rho: 10


shape: [1, 512, 16]