#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_STFT.EDM_STFT"

#defaults: 
#  - shared

# SDE hyperparameters
type: "ve_karras"
sde_hp:
  sigma_data: 0.1 #default for maestro
  sigma_min: 5e-5
  sigma_max: 40
  rho: 10
  max_sigma: 10

stft:
  n_fft: 1534
  hop_length:  384
  center: True
  onesided: True
  compression_alpha: 0.5
  compression_beta: 0.15
  N_pad_spec: 64
  audio_len: 262144

default_shape: [1, 4,  768, 704]