#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.edm_style_multitrack.EDM_Style_Multitrack"

# SDE hyperparameters
type: "ve_karras"

AE_type: "CLAP" #used for encoding the context

FXenc_args:
  type: "fx_encoder+AFv2"

  #ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/tmp/afx-rep.ckpt"

sample_rate: 44100

cfg_dropout_prob: 0.2

sde_hp:
  sigma_data: 0.0716 #default for maestro
  sigma_min: 2e-3
  sigma_max: 20
  max_sigma: 20
  rho: 10

MERT_args:
  layer: 8, #use the last layer of the MERT model
  average: True #if True, the features will be averaged over time
  normalize: True

CLAP_args:
    ckpt_path: "/data5/eloi/checkpoints/laion_clap/music_audioset_epoch_15_esc_90.14.patched.pt"
    distance_type: "cosine"
    normalize: True #if True, the features will be normalized
    use_adaptor: False #if True, the features will be adapted to the CLAP space
    adaptor_checkpoint: Null
    adaptor_type: Null
    add_noise: False #if True, the features will be augmented with orthogonal noise
    noise_sigma: 0.1 #sigma of the orthogonal noise to

fx_encoder_plusplus_args:
    distance_type: "cosine"
    ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/utils/feature_extractors/ckpt/fxenc_plusplus_default.pt"

apply_fxnormaug: False
fxnormaug_train:
  _target_: fx_model.fxnormaug_v0.FxNormAug
  sample_rate: 44100
  mode: "train"
  device: "cuda"

fxnormaug_inference:
  _target_: fx_model.fxnormaug_v0.FxNormAug
  sample_rate: 44100
  mode: "inference"
  device: "cuda"

default_shape: [1,3, 64, 3] 

