test:
  _target_: datasets.eval_benchmark.Eval_Benchmark


  segment_length: 525312
  fs: 44100
  num_tracks: -1
  num_examples: -1
  num_segments_per_track: -1

  format: "all_tracks"
  mode: "dry-only"

  path: /data4/eloi/test_set/audio_material_longer

  RMS_threshold_dB: -60.0
 



