test:
  _target_: datasets.eval_benchmark.Eval_Benchmark


  segment_length: 525312
  fs: 44100
  num_tracks: -1
  num_examples: -1
  num_segments_per_track: -1

  format: "4instr"
  mode: "dry-only"

  path: /data5/eloi/test_set/MDX_TM_benchmark

  RMS_threshold_dB: -60.0
 



