
train:
  _target_: "datasets.tency1_vocals_fxnorm.Tency1_FxNorm_Vocals"
  base_dir: "/data3/martinez/tency1_4instr/train"
  skip_list: []
  subdirs: ["part0", "part1", "part2", "part3","part4", "part5", "part6"]
  segment_length: 525312
  fs: 44100
  stereo: True



  #discard the sample if it contains silence
  RMS_threshold_dB: -40.0

  #random seed
  seed: 42

validation:
  _target_: "datasets.tency1_vocals_fxnorm.Tency1_FxNorm_Vocals_Test"
  base_dir: "/data3/martinez/tency1_4instr/val"
  skip_list: []
  subdirs: ["part5_validation"]
  segment_length: 525312
  fs: 44100
  stereo: True




  num_examples: 4

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

