
train:
  _target_: "datasets.tency_vocals.TencyMastering_Vocals"
  base_dir: "/data2/share/TencyMastering"
  skip_list: ["part1/6699", "part1/33787", "part1/65486", "part1/66235", "part2/67570", "part2/67808", "part3/12212", "part3/67437", "part4_validation/67476", "part2/67658", "part2/67719", "part4_validation/10356"]
  subdirs: ["part1", "part2", "part3"]
  segment_length: 525312
  fs: 44100
  stereo: True

  align: False

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: Null
    #normalize_mode: "rms_dry"
    #rms_dry: -18

  #discard the sample if it contains silence
  RMS_threshold_dB: -40.0

  #random seed
  seed: 42

validation:
  _target_: datasets.tency_vocals.TencyMastering_Vocals_Test
  base_dir: "/data2/share/TencyMastering"
  skip_list: ["part1/6699", "part1/33787", "part1/65486", "part1/66235", "part2/67570", "part2/67808", "part3/12212", "part3/67437", "part4_validation/67476", "part2/67658", "part2/67719", "part4_validation/10356"]
  subdirs: ["part4_validation"]
  segment_length: 525312
  fs: 44100
  stereo: True

  align: False

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    normalize_mode: Null


  num_examples: 4

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

