
test:
  _target_: datasets.tency_mastering_vocals_test.TencyMastering_Vocals_Test
  base_dir: "/data2/share/TencyMastering"
  processed_dir: "/data4/eloi/TencyMastering_fxnorm/part4_test_vocals"
  mode: "wetfxnorm-wet"
  skip_list: ["part1/6699", "part1/33787", "part1/65486", "part1/66235", "part2/67570", "part2/67808", "part3/12212", "part3/67437", "part4_validation/67476", "part2/67658", "part2/67719", "part4_validation/10356"]
  subdirs: ["part4_test"]
  segment_length: 525312
  fs: 44100
  stereo: True

  align: True
  align_mode: "pickle"

  normalize_params:
    normalize_mode: Null
    loudness_dry: Null
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  num_examples: 100

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

