
train:
  _target_: datasets.tency_mastering_vocals.TencyMastering_Vocals
  base_dir: "/data5/eloi/TencyMastering_vocals/train"
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True

  align: False
  align_mode: "pickle"

  normalize_params:
    normalize_mode: "loudness_dry"
    loudness_dry: -18.0
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  x_as_mono: True

  num_examples: -1

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation:
  _target_: datasets.tency_mastering_vocals.TencyMastering_Vocals_Test
  base_dir: "/data5/eloi/TencyMastering_vocals/validation"
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True

  align: False
  align_mode: "pickle"

  normalize_params:
    normalize_mode: "loudness_dry"
    loudness_dry: -18.0
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  num_examples: 100

  x_as_mono: True

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42



test:
  _target_: datasets.tency_mastering_vocals.TencyMastering_Vocals_Test
  base_dir: "/data5/eloi/TencyMastering_vocals/test"
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True

  align: False
  align_mode: "pickle"


  normalize_params:
    normalize_mode: "loudness_dry"
    loudness_dry: -18.0
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  num_examples: 100

  x_as_mono: True

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

