
train:
  _target_: datasets.tency_mastering_multitrack_random.TencyMastering
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True
  only_dry: True

  random_order: True
  random_polarity: True
  random_shift: 16 #shift in samples to apply to the audio, if random

  tracks: "all"

  path_csv: "/data5/eloi/TencyMastering/PANNs_country_pop/train_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null



  num_examples: -1

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation:
  _target_: datasets.tency_mastering_multitrack_simulated.TencyMastering_Test
  mode: "dry-wet"

  random_order: True
  random_num_tracks: False

  only_dry: False

  segment_length: 525312
  fs: 44100
  stereo: True
  #num_tracks: 10
  num_tracks: -1
  #num_tracks: 5

  tracks: ["vocals","bass","drums"]
  clusters: [0,1]

  path_csv: "/data5/eloi/TencyMastering/PANNs_country_pop/val_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  num_examples: -1


  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation_2:
  _target_: datasets.tency_mastering_multitrack_simulated.TencyMastering_Test

  random_order: True
  random_num_tracks: False

  mode: "dry-wet-train"
  segment_length: 525312
  fs: 44100
  stereo: True

  only_dry: False

  #num_tracks: 10
  num_tracks: 36
  #num_tracks: 5

  tracks: ["vocals","bass","drums"]
  clusters: [0,1]

  path_csv: "/data5/eloi/TencyMastering/PANNs_country_pop/train_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  num_examples: -1

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42


test:
  _target_: datasets.tency_mastering_multitrack_paired.TencyMastering_Test


  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True


  tracks: "all"
  only_dry: True

  path_csv: "/data5/eloi/TencyMastering/PANNs_country_pop/test_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  num_examples: 100


  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42



