
_target_: networks.wun_no_condition.Waveunet

num_inputs: 4
num_outputs: 2
num_channels: [24, 48, 96, 96, 192]
instruments: ["mixture"]
kernel_size: 5
target_output_size: 529084
conv_type: "gn_leaky"
res: "fixed"
depth: 1
strides: 1





