#Elucidated Diffusion Model (Karras et al. 2022)
_target_: "diff_params.FM_STFT.FM_STFT"

#defaults: 
#  - shared

# SDE hyperparameters
type: "ve_karras"

cfg_dropout_prob: 0.2

sde_hp:
  sigma_data: 0.1
  sigma_min: 1e-4 #default for maestro
  sigma_max: 1
  max_sigma: 1

sigma_T: 1

stft:
  n_fft: 1534
  hop_length:  384
  center: True
  onesided: True
  compression_alpha: 0.5
  compression_beta: 0.15
  N_pad_spec: 64
  audio_len: 525312

default_shape: [1,4, 4,  768, 704]
