_target_: networks.ncsnpp_multitrack_v2.NCSNpp

  
nonlinearity: 'swish'
nf: 64
ch_mult: [1, 1, 2, 4, 4, 4]
num_res_blocks: 2
attn_resolutions: []
resamp_with_conv: True
time_conditional: True
fir: False
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: 'biggan'
progressive: 'output_skip'
progressive_input: 'input_skip'
progressive_combine: 'sum'
init_scale: 0.
fourier_scale: 16
image_size: 256
embedding_type: 'fourier'
input_channels: 32
output_channels: 16
spatial_channels: 1
dropout: 0
centered: True
discriminative: False