
train:
  _target_: datasets.tency_mastering_simulated.TencyMastering
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True

  tracks: ["vocals"]

  path_csv: "/data5/eloi/TencyMastering/MSCLAP_emb_selected/train_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  clusters: [0,1]

  x_as_mono: True

  num_examples: -1

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation:
  _target_: datasets.tency_mastering_simulated.TencyMastering_Test
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True
  num_tracks: -1

  tracks: ["vocals"]
  clusters: [0,1]

  path_csv: "/data5/eloi/TencyMastering/MSCLAP_emb_selected/val_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  num_examples: -1

  x_as_mono: True

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation_2:
  _target_: datasets.tency_mastering_simulated.TencyMastering_Test
  mode: "dry-wet-train"
  segment_length: 525312
  fs: 44100
  stereo: True

  #num_tracks: 2
  num_tracks: 50

  tracks: ["vocals"]
  clusters: [0,1]

  path_csv: "/data5/eloi/TencyMastering/MSCLAP_emb_selected/train_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: "rms_dry"
    #rms_dry: -18
    #normalize_mode: Null

  num_examples: -1

  x_as_mono: True

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42



test:
  _target_: datasets.tency_mastering_simulated.TencyMastering_Test
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True


  clusters: [0,1]

  tracks: ["vocals"]

  path_csv: "/data5/eloi/TencyMastering/MSCLAP_emb_selected/test_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  num_examples: 100

  x_as_mono: True

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

