
train:
  _target_: datasets.TencyMastering_singletrack.TencyMastering
  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True
  only_dry: False

  apply_effects_on_dry: True #if True, the dry signal will be augmented with effects

  random_polarity: True
  random_shift: 0 #shift in samples to apply to the audio, if random

  tracks: "all"

  path_csv: "conf/data/TencyMastering_train_split.csv"

  RIR_path_csv: "/data4/eloi/ImpulseResponses/rir_files_train.csv"

  normalize_params:
    normalize_mode: "rms_dry"
    rms_dry: -25

  num_examples: -1

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation:
  _target_: datasets.TencyMastering_singletrack.TencyMastering_Test
  mode: "validation"


  only_dry: False

  segment_length: 525312
  fs: 44100
  stereo: True
  num_tracks: -1

  tracks: "all"

  path_csv: "conf/data/TencyMastering_val_split.csv"


  normalize_params:
    normalize_mode: "rms_dry"
    rms_dry: -25

  num_examples: 256


  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42

validation_2:
  _target_: datasets.TencyMastering_singletrack.TencyMastering_Test
  mode: "train"


  segment_length: 525312
  fs: 44100
  stereo: True

  only_dry: False

  num_tracks: 36

  tracks: "all" 

  path_csv: "conf/data/TencyMastering_train_split.csv"


  normalize_params:
    normalize_mode: "rms_dry"
    rms_dry: -25

  num_examples: 256

  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42


test:
  _target_: datasets.TencyMastering_singletrack.TencyMastering_Test


  mode: "dry-wet"
  segment_length: 525312
  fs: 44100
  stereo: True


  tracks: "all"
  only_dry: False

  path_csv: "/data2/eloi/TencyMastering/PANNs_country_pop/test_split.csv"

  normalize_params:
    #normalize_mode: "loudness_dry"
    #loudness_dry: -18.0
    normalize_mode: "rms_dry"
    rms_dry: -25
    #normalize_mode: Null

  num_examples: 100


  RMS_threshold_dB: -40.0
 
  #random seed
  seed: 42



