name: "2nd-order-Heun-unconditional" #same as the file name, try to do that for all testers

tester:
  _target_: 'testing.tester.Tester'

sampler:
  _target_: 'inference.sampler_euler_heun.SamplerEulerHeun'

modes: ["conditional_dry_vocals"] #modes to test


compute_metrics: True #if true, the metrics will be computed after sampling
metrics: ["pairwise-spectral", "pairwise-panning", "pairwise-dynamic", "pairwise-loudness", "pairwise-mss-lr", "pairwise-mss-ms" ]

checkpoint: None

sampling_params:
  same_as_training: False #if true, the sampling parameters will be the same as the ones used for training (sigma_data, sigma_min, sigma_max and rho)
  sde_hp:
    sigma_data: 0.05 #default for maestro
    sigma_min: 1e-4
    sigma_max: 10 #this is sigma_start
    rho: 10
  Schurn: 20
  Snoise: 1
  Stmin: 0
  Stmax: 10
  order: 1 #order of the sampler (1 or 2)
  T: 51 #number of discretization steprs
  schedule: "edm" #"log": log schedule using the parameters in sampling_params

cfg_scale: 1.0

#experiment configuration for different testing modes

unconditional:
  num_samples: 1
  audio_len: 525312


#logging configuration
wandb:
  use: True
  entity: "eloimoliner"
  project: "project_test"
  num_examples_to_log: 8
  log_every: 10
  run_name: "test-conditional-dry-vocals-diffSTFT"