
_target_: "networks.dit.DiffusionTransformer"

io_channels: 64
embed_dim: 512
depth: 16
num_heads: 16
cond_token_dim: 64
global_cond_dim: 0
input_concat_dim: 0
project_cond_tokens: false
transformer_type: "continuous_transformer"