
_target_: "networks.dit_v2.DiffusionTransformer"

io_channels: 64
embed_dim: 512
depth: 16
num_heads: 18
cond_token_dim: 64
global_cond_dim: 0
input_concat_dim: 0
project_cond_tokens: false
transformer_type: "continuous_transformer"

pos_emb_strategy: "concatenation"
pos_emb_dim: 64 # now dimension is 512+64       16 (+1) ideal for AFxRep  (size 512 x 2= 1024 = 64 x 16)
pos_emb_type: "one-hot"

pos_emb_crossattn_strategy: "concatenation"
pos_emb_crossattn_dim: 32 # now dimension is 64+32  ideal for MERT (size 768 = 64 x 12)
pos_emb_crossattn_type: "one-hot"
