_target_: networks.ncsnpp_mapper_CLAP_diffusion.NCSNppTimeFxModel
stft:
  n_fft: 1534
  hop_length:  384
  center: True
  onesided: True
  compression: 1
  N_pad_spec: 64
  
use_context_phases: True #if True, the context phases will be used in the model

nonlinearity: 'swish'
embed_dim: 2624 #2048 (fxencodr) + 512 (CLAP) + 64 (fourier features from AF)
nf: 32
ch_mult: [1, 2, 2, 2, 4]
num_res_blocks: 2
attn_resolutions: []
resamp_with_conv: True
time_conditional: True
fir: False
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: 'bigganfilm'
progressive: 'output_skip'
progressive_input: 'input_skip'
progressive_combine: 'sum'
init_scale: 0.
fourier_scale: 16
image_size: 256
embedding_type: 'fourier'
input_channels: 6
output_channels: 4
spatial_channels: 1
dropout: 0
centered: True
discriminative: False

use_CLAP: True #if True, the CLAP features will be used as conditioning

CLAP_args:
  ckpt_path: "/data5/eloi/checkpoints/laion_clap/music_audioset_epoch_15_esc_90.14.patched.pt"
  distance_type: "cosine"
  normalize: True #if True, the features will be normalized
  use_adaptor: False #if True, the features will be adapted to the CLAP space
  adaptor_checkpoint: "/data5/eloi/experiments/CLAP_regressor_sim_multitrack/MLP_CLAP_regressor-5000.pt"
  adaptor_type: "MLP_CLAP_regressor"
  add_noise: False #if True, the features will be augmented with  noise
  noise_sigma: 0.022 #sigma of the  noise to
