
_target_: "networks.mapper_architectures.TCNModel"

ninputs: 1
noutputs: 2
cond_dim: 1024
nblocks: 14
kernel_size: 15
stride: 1
dilation_growth: 2
channel_growth: 1
channel_width: 128 
stack_size: 15
grouped: False
causal: False
skip_connections: False


use_CLAP: True #if True, the CLAP features will be used as conditioning

CLAP_args:
  ckpt_path: "/data5/eloi/checkpoints/laion_clap/music_audioset_epoch_15_esc_90.14.patched.pt"
  distance_type: "cosine"
  normalize: True #if True, the features will be normalized
  use_adaptor: False #if True, the features will be adapted to the CLAP space
  adaptor_checkpoint: "/data5/eloi/experiments/CLAP_regressor_sim_multitrack/MLP_CLAP_regressor-5000.pt"
  adaptor_type: "MLP_CLAP_regressor"
  add_noise: False #if True, the features will be augmented with  noise
  noise_sigma: 0.022 #sigma of the  noise to
