
defaults:
  - dset: tencymastering_multitrack_4mapper_paired_server5
  - logging: base_logging
  - tester: evaluate_mapper

model_dir: "/data4/eloi/experiments/mapper_blackbox_TCN"


evaluation:
  metrics: ["mss_mslr",] #list of metrics to use for evaluation, currently only mss_mslr is supported

exp:

  data_type: "paired"

  exp_name: "mapper_blackbox_TCN" #name of the experiment

  #related to optimization
  optimizer:
    _target_: "torch.optim.AdamW"
    lr: 1e-4 #            help='Learning rate',
    betas: [0.9, 0.999]
    eps: 1e-8 #for numerical stability, we may need to modify it if usinf fp16
    weight_decay: 0.01 #weight decay for the optimizer

  FXenc_args:
    type: "fx_encoder2048+AFv3" #used for encoding the style effects

  loss:
    type: "MSS_mslr"

  rms_normalize_y: True #if True, the target y will be normalized to a fixed RMS value

  CLAP_args:
    ckpt_path: "/data5/eloi/checkpoints/laion_clap/music_audioset_epoch_15_esc_90.14.patched.pt"
    distance_type: "cosine"
    normalize: True #if True, the features will be normalized
    use_adaptor: False #if True, the features will be adapted to the CLAP space
    adaptor_checkpoint: Null
    adaptor_type: Null
    add_noise: False #if True, the features will be augmented with orthogonal noise
    noise_sigma: 0.1 #sigma of the orthogonal noise to

  
  AFxRep_args:
    distance_type: "cosine" #distance metric to use for the AFxRep
    ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/tmp/afx-rep.ckpt"

  fx_encoder_plusplus_args:
    distance_type: "cosine"
    ckpt_path: "/home/eloi/projects/project_mfm_eloi/src/utils/feature_extractors/ckpt/fxenc_plusplus_default.pt"


  lr_rampup_it: 10 

  #for lr scheduler (not noise schedule!!) TODO (I think)
  scheduler_step_size: 60000
  scheduler_gamma: 0.8

  batch_size: 8

  val_batch_size: 4

  # Performance-related.
  num_workers: 8

  # I/O-related. moved to logging
  seed: 1 # random seed

  resume: False
  resume_checkpoint: None

  #audio data related
  sample_rate: 44100
  stereo: True
  #audio_len: 525312
  audio_len: 524288

  ema_rate: 0.999  
  ema_rampup: 1000  #linear rampup to ema_rate   

  RMS_norm: -25 #fixed RMS normalization for evaluation, hardcoded for now


  #gradient clipping
  use_grad_clip: True
  max_grad_norm: 1

  restore : False
  checkpoint_id: None
  align: False

  augmentations:
    list: ["polarity" ]
    polarity:
      prob: 0.5

  compile: True

  max_tracks: Null

#testing (demos)

network:
  _target_: "networks.mixwaveunet.MixWaveUNet"

  ninputs: 1 #number of input channels, currently only 1 is supported
  noutputs: 2 #number of output channels, currently only 2 is supported

  cond_dim: 2112 #dimension of the conditioning vector, currently only 2112 is supported

  use_CLAP: True #if True, the CLAP features will be used as conditioning
  CLAP_args:
    ckpt_path: "/data5/eloi/checkpoints/laion_clap/music_audioset_epoch_15_esc_90.14.patched.pt"
    distance_type: "cosine"
    normalize: True #if True, the features will be normalized
    use_adaptor: False #if True, the features will be adapted to the CLAP space
    adaptor_checkpoint: "/data5/eloi/experiments/CLAP_regressor_sim_multitrack/MLP_CLAP_regressor-5000.pt"
    adaptor_type: "MLP_CLAP_regressor"
    add_noise: False #if True, the features will be augmented with  noise
    noise_sigma: 0.022 #sigma of the  noise to


hydra:
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        exclude_keys: ['path_experiment',
          'hydra.job_logging.handles.file.filename']
